import Link from 'next/link';
import {notFound} from 'next/navigation';
import {CODES,DOMAIN,MAIL,getM} from '../../../../lib/i18n';
import {SERVICE_SLUGS,BRAND} from '../../../../lib/brand';
import {getService,getServices,getCategories,getUi} from '../../../../lib/services';
import {languageAlternates,absolute,breadcrumbSchema,safeJsonLd,OG_LOCALE} from '../../../../lib/seo';
export const dynamicParams=false;
export function generateStaticParams(){return CODES.flatMap(lang=>SERVICE_SLUGS.map(slug=>({lang,slug})))}
export async function generateMetadata({params}){const {lang,slug}=await params,m=await getM(lang),s=getService(m,slug,lang);if(!s)return{};const title=`${s.title} | ${BRAND.name}`,url=absolute(lang,`/services/${slug}`);return{title,description:s.summary,alternates:{canonical:url,languages:languageAlternates(`/services/${slug}`)},robots:{index:true,follow:true},openGraph:{title,description:s.summary,url,siteName:BRAND.name,locale:OG_LOCALE(lang),type:'website'},twitter:{card:'summary_large_image',title,description:s.summary}}}
export default async function ServicePage({params}){const {lang,slug}=await params,m=await getM(lang),u=getUi(lang),service=getService(m,slug,lang);if(!service)notFound();const all=getServices(m,lang),related=all.filter(s=>s.slug!==slug&&s.category===service.category).slice(0,5),category=getCategories(lang).find(c=>c.id===service.category),url=absolute(lang,`/services/${slug}`);const schemas=[{'@context':'https://schema.org','@type':'Service','@id':`${url}#service`,name:service.title,description:service.summary,serviceType:service.title,provider:{'@type':'Organization','@id':`${DOMAIN}/#organization`,name:BRAND.name,url:DOMAIN},url},breadcrumbSchema(lang,[{name:BRAND.name,path:''},{name:category?.title||m.sh,path:`#${service.category}`},{name:service.title,path:`/services/${slug}`}])];
return <main className="w service-page"><nav aria-label="Breadcrumb" className="breadcrumbs"><Link href={`/${lang}`}>{BRAND.name}</Link><span>›</span><Link href={`/${lang}#${service.category}`}>{category?.title||m.sh}</Link><span>›</span><span aria-current="page">{service.title}</span></nav>
<section className="service-hero"><span className="kicker">{BRAND.name} · {BRAND.descriptor}</span><h1>{service.title}</h1><p>{service.summary}</p><div className="hero-actions"><a className="btn p" href={`mailto:${MAIL}?subject=${encodeURIComponent(service.title)}`}>{m.mail}</a><Link className="btn outline" href={`/${lang}#${service.category}`}>{category?.title}</Link></div></section>
<section className="service-content"><div><span className="kicker">{u.overview}</span><h2>{service.title}</h2><p>{service.summary}</p><h3>{u.howHelp}</h3><p>{m.sub}</p><h3>{u.who}</h3><p>{u.independent}</p><h3>{u.next}</h3><div className="process-grid">{m.st.map((x,i)=><div className="process-card" key={i}><span>{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></div><aside><span className="kicker">{u.process}</span>{m.st.map((step,i)=><div className="mini-step" key={i}><b>{i+1}</b><span>{step[0]}</span></div>)}<div className="scope-box"><b>{u.independent}</b><p>{u.independent}</p></div></aside></section>
{related.length>0&&<section className="related"><span className="kicker">{u.related}</span><h2>{u.also}</h2><div className="related-grid">{related.map(r=><Link key={r.slug} href={`/${lang}/services/${r.slug}`}><b>{r.title}</b></Link>)}</div></section>}
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(schemas)}}/></main>}
