import Link from 'next/link';
import {BRAND} from '../../../lib/brand';
import {DOMAIN} from '../../../lib/i18n';
import {languageAlternates} from '../../../lib/seo';
import aboutCopy from '../../../lib/aboutCopy.json';
import {getUi} from '../../../lib/services';

export async function generateMetadata({params}){const {lang}=await params,c=aboutCopy[lang];return {title:`${c.title} | ${BRAND.name}`,description:c.lead,alternates:{canonical:`/${lang}/about`,languages:languageAlternates('/about')},openGraph:{title:`${c.title} | ${BRAND.name}`,description:c.lead,url:`${DOMAIN}/${lang}/about`,siteName:BRAND.name},robots:{index:true,follow:true}}}
export default async function About({params}){const {lang}=await params,c=aboutCopy[lang],u=getUi(lang);return <main id="main-content" className="w standalone-page about-page"><div className="page-intro"><span className="kicker">POA DUBAI</span><h1>{c.title}</h1><p>{c.lead}</p></div><section className="about-lead"><p>{c.intro}</p></section><div className="about-grid"><section className="about-card about-card-feature"><span className="about-number">01</span><h2>{c.start}</h2><p>{c.startText}</p></section><section className="about-card"><span className="about-number">02</span><h2>{c.how}</h2><p>{c.howText}</p></section><section className="about-card"><span className="about-number">03</span><h2>{c.role}</h2><p>{c.roleText}</p></section><section className="about-card"><span className="about-number">04</span><h2>{c.why}</h2><p>{c.whyText}</p></section></div><section className="about-authorities"><span className="about-number">05</span><h2>{c.authoritiesTitle}</h2><p>{c.authoritiesText}</p><div className="authority-grid">{c.authorities.map((authority)=><div className="authority-item" key={authority}>{authority}</div>)}</div><p className="authority-note">{c.authoritiesNote}</p><p className="authority-cta">{c.authoritiesCta}</p></section><section className="about-cta"><div><span className="kicker">POA DUBAI</span><h2>{c.cta}</h2><p>{c.ctaText}</p></div><Link className="btn primary" href={`/${lang}/contact`}>{u.contact}</Link></section></main>}
