const COPY={
 en:'Depending on the receiving authority, the same transaction may also require',
 de:'Je nach empfangender Stelle kann derselbe Vorgang außerdem Folgendes erfordern:',
 fr:'Selon l’autorité destinataire, la même démarche peut également nécessiter',
 es:'Según la entidad receptora, el mismo trámite también puede requerir',
 it:'A seconda dell’autorità destinataria, la stessa pratica può richiedere anche',
 pt:'Consoante a entidade destinatária, o mesmo processo também pode exigir',
 nl:'Afhankelijk van de ontvangende instantie kan dezelfde procedure ook het volgende vereisen:',
 pl:'W zależności od organu odbierającego ta sama sprawa może również wymagać',
 sv:'Beroende på den mottagande myndigheten kan samma ärende även kräva',
 ro:'În funcție de autoritatea destinatară, aceeași procedură poate necesita și',
 el:'Ανάλογα με την αρχή παραλαβής, η ίδια διαδικασία μπορεί επίσης να απαιτεί',
 cs:'Podle přijímajícího orgánu může stejný postup vyžadovat také',
 da:'Afhængigt af den modtagende myndighed kan den samme sag også kræve',
 fi:'Vastaanottavasta viranomaisesta riippuen sama asia voi edellyttää myös seuraavia palveluja:',
 hu:'A fogadó hatóságtól függően ugyanaz az ügy további szolgáltatásokat is igényelhet:',
 bg:'В зависимост от приемащия орган същата процедура може да изисква и',
 hr:'Ovisno o tijelu koje prima dokument, isti postupak može zahtijevati i',
 sk:'V závislosti od prijímajúceho orgánu môže ten istý postup vyžadovať aj',
 sl:'Odvisno od organa prejemnika lahko isti postopek zahteva tudi',
 et:'Sõltuvalt vastuvõtvast asutusest võib sama toiming nõuda ka järgmisi teenuseid:',
 lv:'Atkarībā no saņēmējas iestādes tam pašam procesam var būt nepieciešami arī šādi pakalpojumi:',
 lt:'Priklausomai nuo dokumentą priimančios institucijos, tam pačiam procesui taip pat gali reikėti',
 mt:'Skont l-awtorità li tirċievi d-dokument, l-istess proċess jista’ jeħtieġ ukoll',
 ga:'Ag brath ar an údarás glactha, d’fhéadfadh an próiseas céanna na seirbhísí seo a leanas a éileamh freisin:',
 no:'Avhengig av mottakende myndighet kan den samme saken også kreve',
 tr:'Belgeyi kabul edecek kuruma bağlı olarak aynı işlem ayrıca şunları gerektirebilir:',
 sr:'U zavisnosti od organa koji prima dokument, isti postupak može zahtevati i',
 uk:'Залежно від органу, який приймає документ, та сама процедура може також потребувати',
 sq:'Në varësi të autoritetit pritës, e njëjta procedurë mund të kërkojë gjithashtu',
 is:'Eftir því hvaða yfirvald tekur við skjalinu getur sama ferli einnig krafist',
 ru:'В зависимости от принимающего органа та же процедура может также потребовать',
 ar:'بحسب الجهة التي ستستلم المستند، قد تتطلب المعاملة نفسها أيضًا'
};
export function semanticLinkLead(lang){return COPY[lang]||COPY.en;}
