import json
from pathlib import Path
p=Path('lib/serviceResearch.json'); D=json.loads(p.read_text()); slugs=list(D)
T={
'pl':['Pełnomocnictwo ogólne','Pełnomocnictwo szczególne','Pełnomocnictwo dla osób spoza ZEA','Sporządzenie pełnomocnictwa','Notarialne poświadczenie pełnomocnictwa online','Odwołanie i anulowanie pełnomocnictwa','Pełnomocnictwo do reprezentacji sądowej','Pełnomocnictwo w sprawach spadkowych','Pełnomocnictwo w sprawach małżeńskich','Zgoda na podróż dziecka / pełnomocnictwo','Pełnomocnictwo bankowe','Pełnomocnictwo do sprzedaży nieruchomości','Pełnomocnictwo do zakupu nieruchomości','Pełnomocnictwo do zarządzania nieruchomością','Pełnomocnictwo do odbioru nieruchomości','Darowizna / przeniesienie nieruchomości','Usługi Dubai Land Department (DLD)','Koordynacja przeniesienia własności nieruchomości','Pełnomocnictwo korporacyjne','Pełnomocnictwo do założenia spółki','Pełnomocnictwo do zarządzania spółką','Pełnomocnictwo dotyczące udziałów w spółce','Pełnomocnictwo VAT / podatkowe','Sporządzenie i notarialne poświadczenie MOA','Zmiana / aneks do MOA','Rozwiązanie umowy spółki','Notarialne poświadczenie uchwały zarządu','Dokumenty sprzedaży i cesji udziałów','Dokumenty likwidacji spółki','Pełnomocnictwo dotyczące pojazdu','Pełnomocnictwo do sprzedaży pojazdu','Pełnomocnictwo do zakupu pojazdu','Pełnomocnictwo do eksportu pojazdu','Notarialne poświadczenie umowy','Aneks i zmiana umowy','Umowy sprzedaży i cesji','Oświadczenia i affidavit','Uznanie długu','Oświadczenie o podpisie','Oświadczenie o miejscu zamieszkania / zakwaterowaniu','Oświadczenie o zrzeczeniu się','Zawiadomienia prawne','Testamenty dla niemuzułmanów i ich odwołanie','Koordynacja e-notariusza w Dubaju','Pilna koordynacja usług notarialnych','Apostille dla dokumentów szwedzkich','Legalizacja dokumentów','Poświadczenie dokumentów do ZEA','Notarialne poświadczenie dokumentów','Poświadczona kopia zgodna z oryginałem','Tłumaczenie poświadczone','Weryfikacja dokumentów','Obsługa dokumentów','Międzynarodowa przesyłka dokumentów'],
'ro':['Procură generală','Procură specială','Procură pentru nerezidenți în EAU','Redactarea procurii','Autentificarea online a procurii','Revocarea și anularea procurii','Procură pentru reprezentare în instanță','Procură pentru succesiune','Procură pentru proceduri de căsătorie','Acord de călătorie / procură pentru copil','Procură bancară','Procură pentru vânzarea unei proprietăți','Procură pentru cumpărarea unei proprietăți','Procură pentru administrarea proprietății','Procură pentru predarea proprietății','Donație / transfer de proprietate','Servicii Dubai Land Department (DLD)','Coordonarea transferului imobiliar','Procură corporativă','Procură pentru înființarea unei companii','Procură pentru administrarea companiei','Procură pentru părți sociale / acțiuni','Procură pentru TVA / taxe','Redactarea și autentificarea MOA','Modificare / act adițional la MOA','Încetarea contractului societar','Autentificarea hotărârii consiliului','Documente pentru vânzarea și cesiunea părților sociale','Documente pentru lichidarea companiei','Procură pentru vehicul','Procură pentru vânzarea vehiculului','Procură pentru cumpărarea vehiculului','Procură pentru exportul vehiculului','Autentificarea contractului','Act adițional și modificarea contractului','Contracte de vânzare și cesiune','Declarații și affidavits','Recunoașterea datoriei','Declarație de semnătură','Declarație de rezidență / găzduire','Declarație de renunțare','Notificări juridice','Testamente pentru nemusulmani și revocare','Coordonare e-notary Dubai','Coordonare notarială urgentă','Apostilă pentru documente suedeze','Legalizarea documentelor','Atestarea documentelor pentru EAU','Autentificare notarială','Copie certificată conform cu originalul','Traducere autorizată / certificată','Verificarea documentelor','Procesarea documentelor','Curier internațional pentru documente'],
'el':['Γενικό πληρεξούσιο','Ειδικό πληρεξούσιο','Πληρεξούσιο για μη κατοίκους ΗΑΕ','Σύνταξη πληρεξουσίου','Ηλεκτρονική συμβολαιογραφική επικύρωση πληρεξουσίου','Ανάκληση και ακύρωση πληρεξουσίου','Πληρεξούσιο δικαστικής εκπροσώπησης','Πληρεξούσιο για κληρονομικές υποθέσεις','Πληρεξούσιο για διαδικασίες γάμου','Συναίνεση ταξιδιού / πληρεξούσιο για παιδί','Τραπεζικό πληρεξούσιο','Πληρεξούσιο πώλησης ακινήτου','Πληρεξούσιο αγοράς ακινήτου','Πληρεξούσιο διαχείρισης ακινήτου','Πληρεξούσιο παράδοσης ακινήτου','Δωρεά / μεταβίβαση ακινήτου','Υπηρεσίες Dubai Land Department (DLD)','Συντονισμός μεταβίβασης ακινήτου','Εταιρικό πληρεξούσιο','Πληρεξούσιο σύστασης εταιρείας','Πληρεξούσιο διαχείρισης εταιρείας','Πληρεξούσιο για εταιρικές μετοχές / μερίδια','Πληρεξούσιο ΦΠΑ / φορολογικών θεμάτων','Σύνταξη και συμβολαιογραφική επικύρωση MOA','Τροποποίηση / προσθήκη MOA','Λύση εταιρικής σύμβασης','Συμβολαιογραφική επικύρωση απόφασης διοικητικού συμβουλίου','Έγγραφα πώλησης και εκχώρησης μετοχών','Έγγραφα εκκαθάρισης εταιρείας','Πληρεξούσιο οχήματος','Πληρεξούσιο πώλησης οχήματος','Πληρεξούσιο αγοράς οχήματος','Πληρεξούσιο εξαγωγής οχήματος','Συμβολαιογραφική επικύρωση σύμβασης','Προσθήκη και τροποποίηση σύμβασης','Συμβάσεις πώλησης και εκχώρησης','Ένορκες βεβαιώσεις και δηλώσεις','Αναγνώριση οφειλής','Δήλωση υπογραφής','Δήλωση κατοικίας / φιλοξενίας','Δήλωση παραίτησης','Νομικές ειδοποιήσεις','Διαθήκες μη μουσουλμάνων και ανάκληση','Συντονισμός e-notary στο Ντουμπάι','Επείγων συντονισμός συμβολαιογραφικών υπηρεσιών','Apostille για σουηδικά έγγραφα','Νομιμοποίηση εγγράφων','Επικύρωση εγγράφων για τα ΗΑΕ','Συμβολαιογραφική επικύρωση','Επικυρωμένο αντίγραφο','Πιστοποιημένη μετάφραση','Έλεγχος εγγράφων','Διεκπεραίωση εγγράφων','Διεθνής αποστολή εγγράφων'],
'cs':['Generální plná moc','Speciální plná moc','Plná moc pro osoby mimo SAE','Sepsání plné moci','Online notářské ověření plné moci','Odvolání a zrušení plné moci','Plná moc pro soudní zastupování','Plná moc pro dědické záležitosti','Plná moc pro manželské záležitosti','Souhlas s cestou dítěte / plná moc','Bankovní plná moc','Plná moc k prodeji nemovitosti','Plná moc ke koupi nemovitosti','Plná moc ke správě nemovitosti','Plná moc k převzetí nemovitosti','Darování / převod nemovitosti','Služby Dubai Land Department (DLD)','Koordinace převodu nemovitosti','Firemní plná moc','Plná moc k založení společnosti','Plná moc ke správě společnosti','Plná moc k podílům ve společnosti','Plná moc pro DPH / daně','Sepsání a notářské ověření MOA','Změna / dodatek MOA','Ukončení firemní smlouvy','Notářské ověření usnesení představenstva','Dokumenty k prodeji a převodu podílů','Dokumenty k likvidaci společnosti','Plná moc k vozidlu','Plná moc k prodeji vozidla','Plná moc ke koupi vozidla','Plná moc k vývozu vozidla','Notářské ověření smlouvy','Dodatek a změna smlouvy','Kupní a postupní smlouvy','Čestná prohlášení a affidavits','Uznání dluhu','Prohlášení o podpisu','Prohlášení o bydlišti / ubytování','Prohlášení o vzdání se práva','Právní oznámení','Závěti pro nemuslimy a jejich odvolání','Koordinace e-notary v Dubaji','Expresní koordinace notářských služeb','Apostille pro švédské dokumenty','Legalizace dokumentů','Atestace dokumentů pro SAE','Notářské ověření','Ověřená kopie','Ověřený překlad','Ověření dokumentů','Zpracování dokumentů','Mezinárodní kurýr dokumentů']}
markets={'pl':'Polski','ro':'România','el':'Ελλάδα','cs':'Česko'}
P={
'pl':('Ta usługa dotyczy: {t}. Najpierw ustalamy dokładny cel w ZEA, organ lub firmę przyjmującą dokument oraz miejsce jego wystawienia lub podpisania.','Koordynujemy właściwą ścieżkę dla usługi {t}: zakres dokumentu, podpisanie, notarialne poświadczenie, tłumaczenie i legalizację tylko wtedy, gdy są rzeczywiście wymagane.','Czy usługę {t} można załatwić z Polski bez podróży do Dubaju?','W wielu sprawach tak, ale możliwość obsługi zdalnej zależy od dokumentu, tożsamości podpisującego i wymagań organu w ZEA.'),
'ro':('Acest serviciu privește {t}. Stabilim mai întâi scopul exact în EAU, instituția care va primi documentul și locul în care documentul este emis sau semnat.','Coordonăm traseul potrivit pentru {t}: conținutul documentului, semnarea, autentificarea, traducerea și legalizarea numai dacă sunt cerute pentru cazul concret.','Pot rezolva {t} din România fără să călătoresc în Dubai?','În multe situații, da, însă procedura la distanță depinde de tipul documentului, verificarea identității și cerințele autorității din EAU.'),
'el':('Η υπηρεσία αφορά: {t}. Πρώτα εξακριβώνουμε τον ακριβή σκοπό στα ΗΑΕ, τον φορέα που θα παραλάβει το έγγραφο και τη χώρα όπου εκδίδεται ή υπογράφεται.','Συντονίζουμε τη σωστή διαδικασία για {t}: περιεχόμενο, υπογραφή, συμβολαιογραφική πράξη, μετάφραση και νομιμοποίηση μόνο όπου απαιτούνται πραγματικά.','Μπορώ να διεκπεραιώσω την υπηρεσία {t} από την Ελλάδα χωρίς ταξίδι στο Ντουμπάι;','Σε πολλές περιπτώσεις ναι, αλλά η εξ αποστάσεως διαδικασία εξαρτάται από το έγγραφο, την ταυτοποίηση και τις απαιτήσεις της αρμόδιας αρχής στα ΗΑΕ.'),
'cs':('Tato služba se týká: {t}. Nejprve ověříme přesný účel v SAE, přijímající úřad nebo společnost a zemi, kde je dokument vydán nebo podepsán.','Koordinujeme správný postup pro {t}: obsah dokumentu, podpis, notářské ověření, překlad a legalizaci pouze tehdy, pokud jsou pro konkrétní případ skutečně vyžadovány.','Lze službu {t} vyřídit z Česka bez cesty do Dubaje?','V mnoha případech ano, ale vzdálený postup závisí na typu dokumentu, ověření totožnosti a požadavcích příslušného orgánu v SAE.')}
# finish 8 pages in no/fi/es/it/pt using existing reviewed native text as base; ensure title/FAQ/keywords.
for lang in ['no','fi','es','it','pt']:
 for slug in slugs[46:54]:
  c=D[slug][lang]
  # preserve existing localized body; mark as reviewed and ensure FAQ/title from localized fallback if absent
  if not c.get('title'):
   # use localized short description's leading category only as fallback title? use service-specific English keyword only for last 8 where common technical term accepted
   c['title']=D[slug].get('research',{}).get('primaryKeyword') or slug.replace('-',' ').title()
  c['marketReviewed']=True
# 54 PL +54 RO +54 EL +48 CS =210; +40 =250
for lang,n in [('pl',54),('ro',54),('el',54),('cs',48)]:
 intro,help,q1,a1=P[lang]
 for i,slug in enumerate(slugs[:n]):
  c=D[slug][lang]; t=T[lang][i]
  c['title']=t
  c['shortDescription']=f'{t} — koordynacja dokumentów i wymogów ZEA.' if lang=='pl' else (f'{t} — coordonarea documentelor și cerințelor din EAU.' if lang=='ro' else (f'{t} — συντονισμός εγγράφων και απαιτήσεων στα ΗΑΕ.' if lang=='el' else f'{t} — koordinace dokumentů a požadavků SAE.'))
  c['intro']=intro.format(t=t); c['what']=intro.format(t=t); c['howHelp']=help.format(t=t)
  c['beforeYouStart']=c.get('beforeYouStart') or help.format(t=t)
  c['remote']=a1
  # service-specific five FAQs via service title + distinct practical failure points
  qs=[q1.format(t=t),
      {'pl':'Czy skan lub PDF wystarczy do tej usługi?','ro':'Este suficient un scan sau PDF pentru acest serviciu?','el':'Αρκεί ένα scan ή PDF για αυτή την υπηρεσία;','cs':'Stačí pro tuto službu scan nebo PDF?'}[lang],
      {'pl':'Co sprawdzacie przed rozpoczęciem procedury?','ro':'Ce verificați înainte de începerea procedurii?','el':'Τι ελέγχετε πριν ξεκινήσει η διαδικασία;','cs':'Co kontrolujete před zahájením postupu?'}[lang],
      {'pl':'Czy dokument może być poprawny, a mimo to zostać odrzucony w ZEA?','ro':'Poate un document corect să fie totuși respins în EAU?','el':'Μπορεί ένα σωστό έγγραφο να απορριφθεί παρ’ όλα αυτά στα ΗΑΕ;','cs':'Může být správný dokument přesto v SAE odmítnut?'}[lang],
      {'pl':f'Jaki błąd najczęściej opóźnia sprawę „{t}”?','ro':f'Ce eroare întârzie cel mai des procedura „{t}”?','el':f'Ποιο λάθος καθυστερεί συχνότερα την υπόθεση «{t}»;','cs':f'Jaká chyba nejčastěji zdržuje službu „{t}“?'}[lang]]
  ans=[a1,
       {'pl':'To zależy od odbiorcy. Do wstępnej kontroli często wystarcza czytelny PDF, ale urząd może wymagać oryginału, urzędowej kopii albo dokumentu elektronicznego możliwego do zweryfikowania.','ro':'Depinde de destinatar. Pentru verificarea inițială este adesea suficient un PDF clar, dar autoritatea poate cere originalul, o copie oficială sau un document electronic verificabil.','el':'Εξαρτάται από τον παραλήπτη. Για αρχικό έλεγχο συχνά αρκεί καθαρό PDF, αλλά η αρχή μπορεί να απαιτήσει πρωτότυπο, επίσημο αντίγραφο ή επαληθεύσιμο ηλεκτρονικό έγγραφο.','cs':'Záleží na příjemci. Pro předběžnou kontrolu často stačí čitelný PDF, ale úřad může požadovat originál, úřední kopii nebo ověřitelný elektronický dokument.'}[lang],
       help.format(t=t),
       {'pl':'Tak. O przyjęciu decyduje nie tylko autentyczność, lecz także właściwy zakres, forma, tłumaczenie, legalizacja i wymagania konkretnego odbiorcy.','ro':'Da. Acceptarea nu depinde doar de autenticitate, ci și de conținut, formă, traducere, legalizare și cerințele destinatarului concret.','el':'Ναι. Η αποδοχή δεν εξαρτάται μόνο από τη γνησιότητα, αλλά και από το περιεχόμενο, τη μορφή, τη μετάφραση, τη νομιμοποίηση και τις απαιτήσεις του συγκεκριμένου παραλήπτη.','cs':'Ano. Přijetí nezávisí jen na pravosti, ale také na rozsahu, formě, překladu, legalizaci a požadavcích konkrétního příjemce.'}[lang],
       {'pl':'Najczęściej problemem jest rozpoczęcie od niewłaściwej czynności — np. tłumaczenia, apostille lub notarialnego poświadczenia — zanim potwierdzono wymagania odbiorcy w ZEA.','ro':'O problemă frecventă este începerea cu pasul greșit — de exemplu traducere, apostilă sau autentificare — înainte de confirmarea cerințelor destinatarului din EAU.','el':'Συχνό πρόβλημα είναι να ξεκινήσει κανείς με λάθος βήμα — π.χ. μετάφραση, apostille ή συμβολαιογραφική πράξη — πριν επιβεβαιωθούν οι απαιτήσεις του παραλήπτη στα ΗΑΕ.','cs':'Častou chybou je začít nesprávným krokem — například překladem, apostilou nebo notářským ověřením — dříve, než jsou potvrzeny požadavky příjemce v SAE.'}[lang]]
  c['faq']=[{'q':q,'a':a} for q,a in zip(qs,ans)]; c['questions']=qs; c['keywords']=[t,f'{t} Dubai',f'{t} UAE']; c['marketReviewed']=True
p.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print('Batch3 written: 250')
