import json
from pathlib import Path
p=Path('lib/serviceResearch.json'); D=json.loads(p.read_text())
slugs=list(D)
# Native service titles for the 46 records in Batch 2. These are editorial labels, not literal SEO stuffing.
titles={
'no': ['Generalfullmakt','Spesialfullmakt','Fullmakt for personer bosatt utenfor UAE','Utarbeidelse av fullmakt','Nettbasert notarialbekreftelse av fullmakt','Tilbakekalling og annullering av fullmakt','Fullmakt for representasjon i rettssaker','Arvefullmakt','Fullmakt i forbindelse med ekteskap','Reisesamtykke / fullmakt for barn','Bankfullmakt','Fullmakt for salg av eiendom','Fullmakt for kjøp av eiendom','Fullmakt for eiendomsforvaltning','Fullmakt for overtakelse av eiendom','Gaveoverføring / overføring av eiendom','Tjenester mot Dubai Land Department (DLD)','Koordinering av eiendomsoverdragelse','Selskapsfullmakt','Fullmakt for selskapsstiftelse','Fullmakt for selskapsledelse','Fullmakt for selskapsandeler','Fullmakt for MVA og skatt','Utarbeidelse og notarialbekreftelse av stiftelsesdokument (MOA)','Endring / tillegg til MOA','Oppsigelse av selskapsavtale','Notarialbekreftelse av styrevedtak','Dokumenter for salg og overdragelse av selskapsandeler','Dokumenter ved selskapsavvikling','Kjøretøyfullmakt','Fullmakt for salg av kjøretøy','Fullmakt for kjøp av kjøretøy','Fullmakt for eksport av kjøretøy','Notarialbekreftelse av kontrakt','Tillegg og endring av kontrakt','Salgs- og overdragelsesavtaler','Erklæringer og affidavits','Gjeldserkjennelse','Signaturerklæring','Bosteds- / innkvarteringserklæring','Avkallserklæring','Juridiske varsler','Testament for ikke-muslimer og tilbakekalling','Koordinering av Dubai e-notary','Hastekoordinering av notartjenester','Apostille for svenske dokumenter'],
'fi': ['Yleisvaltakirja','Erityisvaltakirja','Valtakirja UAE:n ulkopuolella asuvalle','Valtakirjan laatiminen','Valtakirjan verkkonotaarointi','Valtakirjan peruuttaminen ja mitätöinti','Valtakirja oikeudelliseen edustamiseen','Perintöasioiden valtakirja','Avioliittoasioiden valtakirja','Lapsen matkustuslupa / valtakirja','Pankkiasioiden valtakirja','Valtakirja kiinteistön myyntiin','Valtakirja kiinteistön ostoon','Valtakirja kiinteistön hallinnointiin','Valtakirja kiinteistön luovutukseen','Kiinteistön lahjoitus / siirto','Dubai Land Department (DLD) -asioiden koordinointi','Kiinteistökaupan koordinointi','Yritysvaltakirja','Valtakirja yrityksen perustamiseen','Valtakirja yrityksen hallinnointiin','Valtakirja yhtiöosuuksiin','ALV- / veroasioiden valtakirja','MOA:n laatiminen ja notaarivahvistus','MOA:n muutos / lisäys','Yrityssopimuksen päättäminen','Hallituksen päätöksen notaarivahvistus','Osakkeiden myynti- ja luovutusasiakirjat','Yrityksen selvitystilaan liittyvät asiakirjat','Ajoneuvovaltakirja','Valtakirja ajoneuvon myyntiin','Valtakirja ajoneuvon ostoon','Valtakirja ajoneuvon vientiin','Sopimuksen notaarivahvistus','Sopimuksen lisäys ja muutos','Myynti- ja luovutussopimukset','Valaehtoiset vakuutukset ja ilmoitukset','Velan tunnustamista koskeva ilmoitus','Allekirjoitusilmoitus','Asuinpaikka- / majoitusilmoitus','Luopumisilmoitus','Oikeudelliset ilmoitukset','Ei-muslimien testamentit ja peruuttaminen','Dubain sähköisen notaarin koordinointi','Kiireellinen notaaripalvelun koordinointi','Apostille ruotsalaisille asiakirjoille'],
'es': ['Poder general','Poder especial','Poder para no residentes en EAU','Redacción de poderes','Notarización en línea de poderes','Revocación y cancelación de poderes','Poder para representación judicial','Poder para asuntos de herencia','Poder para trámites matrimoniales','Autorización de viaje / poder para menores','Poder para operaciones bancarias','Poder para vender una propiedad','Poder para comprar una propiedad','Poder para administrar una propiedad','Poder para entrega de una propiedad','Donación / transmisión de propiedad','Servicios ante Dubai Land Department (DLD)','Coordinación de compraventa y transmisión inmobiliaria','Poder societario','Poder para constitución de empresa','Poder para gestión de empresa','Poder para participaciones sociales','Poder para IVA / impuestos','Redacción y notarización del Memorandum of Association (MOA)','Modificación / adenda del MOA','Terminación de contratos societarios','Notarización de acuerdos del consejo','Documentos de venta y cesión de participaciones','Documentos para liquidación de empresa','Poder para vehículos','Poder para vender un vehículo','Poder para comprar un vehículo','Poder para exportar un vehículo','Notarización de contratos','Adenda y modificación de contratos','Contratos de compraventa y cesión','Declaraciones juradas y manifestaciones','Reconocimiento de deuda','Declaración de firma','Declaración de residencia / alojamiento','Declaración de renuncia','Notificaciones legales','Testamentos para no musulmanes y revocación','Coordinación de notaría electrónica en Dubái','Coordinación notarial urgente','Apostilla para documentos suecos'],
'it': ['Procura generale','Procura speciale','Procura per non residenti negli EAU','Redazione della procura','Autenticazione notarile online della procura','Revoca e annullamento della procura','Procura per rappresentanza giudiziale','Procura per successione ereditaria','Procura per pratiche matrimoniali','Consenso al viaggio / procura per minori','Procura bancaria','Procura per vendita immobiliare','Procura per acquisto immobiliare','Procura per gestione immobiliare','Procura per consegna dell’immobile','Donazione / trasferimento immobiliare','Servizi presso il Dubai Land Department (DLD)','Coordinamento della compravendita immobiliare','Procura societaria','Procura per costituzione di società','Procura per gestione societaria','Procura per quote societarie','Procura per IVA / imposte','Redazione e autenticazione notarile del Memorandum of Association (MOA)','Modifica / addendum del MOA','Risoluzione di contratto societario','Autenticazione notarile di delibera del consiglio','Documenti per vendita e cessione di quote','Documenti per liquidazione societaria','Procura per veicoli','Procura per vendita di veicolo','Procura per acquisto di veicolo','Procura per esportazione di veicolo','Autenticazione notarile di contratti','Addendum e modifica contrattuale','Contratti di vendita e cessione','Dichiarazioni e affidavit','Dichiarazione di riconoscimento del debito','Dichiarazione di firma','Dichiarazione di residenza / alloggio','Dichiarazione di rinuncia','Notifiche legali','Testamenti per non musulmani e revoca','Coordinamento e-notary a Dubai','Coordinamento notarile urgente','Apostille per documenti svedesi'],
'pt': ['Procuração geral','Procuração especial','Procuração para não residentes nos EAU','Redação de procuração','Reconhecimento notarial online da procuração','Revogação e cancelamento de procuração','Procuração para representação judicial','Procuração para assuntos sucessórios','Procuração para procedimentos de casamento','Autorização de viagem / procuração para menores','Procuração bancária','Procuração para venda de imóvel','Procuração para compra de imóvel','Procuração para gestão de imóvel','Procuração para entrega de imóvel','Doação / transferência de imóvel','Serviços junto do Dubai Land Department (DLD)','Coordenação de transmissão imobiliária','Procuração societária','Procuração para constituição de empresa','Procuração para gestão de empresa','Procuração para participações sociais','Procuração para IVA / impostos','Redação e reconhecimento notarial do Memorandum of Association (MOA)','Alteração / adenda ao MOA','Cessação de contrato societário','Reconhecimento notarial de deliberação do conselho','Documentos de venda e cessão de participações','Documentos para liquidação de empresa','Procuração para veículos','Procuração para venda de veículo','Procuração para compra de veículo','Procuração para exportação de veículo','Reconhecimento notarial de contrato','Adenda e alteração contratual','Contratos de venda e cessão','Declarações e affidavits','Declaração de reconhecimento de dívida','Declaração de assinatura','Declaração de residência / alojamento','Declaração de renúncia','Notificações legais','Testamentos para não muçulmanos e revogação','Coordenação de notário eletrónico no Dubai','Coordenação notarial urgente','Apostila para documentos suecos']}
market={
'no':('Norge','norsk','norske','For dokumenter fra Norge må riktig autentiseringsvei avklares ut fra mottakerlandet og dokumenttypen. Ikke start med apostille eller legalisering før den faktiske mottakeren i EAU er identifisert.'),
'fi':('Finland','finsk','finske','For dokumenter utstedt i Finland må man først avklare hvilken finsk myndighet eller notar som skal bekrefte dokumentet og hvilken legaliseringskjede mottakeren i EAU krever.'),
'es':('España','español','españoles','En España, apostilla y legalización diplomática son vías distintas. Para documentos destinados a EAU conviene confirmar primero el tipo de documento, el original admisible y la cadena exigida por la autoridad receptora.'),
'it':('Italia','italiano','italiani','Per i documenti emessi in Italia destinati agli EAU occorre verificare la catena applicabile prima di iniziare: autorità italiana competente, eventuale traduzione e successiva legalizzazione/attestazione richiesta per l’uso negli Emirati.'),
'pt':('Portugal','português','portugueses','Para documentos emitidos em Portugal, apostila e legalização consular não são sinónimos. O percurso deve ser definido em função do país de destino, do tipo de documento e da entidade que o vai receber nos EAU.')}
phr={
'no':{
'short':'{t} for en UAE-relatert sak, med kontroll av formål, mottaker, fullmakter og dokumentkrav før innsending.',
'intro':'{t} brukes når du trenger å få gjennomført en bestemt handling i De forente arabiske emirater og vil unngå feil dokumenttype, for vide fullmakter eller manglende bekreftelser. Vi starter med hva som faktisk skal gjøres, hvem som skal motta dokumentet og hvor dokumentet utstedes eller signeres.',
'what':'Denne tjenesten gjelder {t}. Innholdet må passe den konkrete transaksjonen; overskriften alene er ikke nok. Banker, DLD, notar, domstol, selskap eller annen mottaker kan stille egne krav til ordlyd, identitet, original, oversettelse og attestering.',
'help':'Vi kartlegger formålet, mottakeren, landet du befinner deg i og hvilke dokumenter du allerede har. Deretter koordinerer vi riktig rekkefølge for utarbeidelse, signering, notarialbekreftelse, oversettelse, legalisering eller attestering når dette er nødvendig.',
'before':'Før saken startes kontrollerer vi navn og passopplysninger, nødvendige fullmakter, vedlegg, språk og om mottakeren krever fysisk original, bekreftet kopi eller verifiserbart digitalt originaldokument. {local}',
'remote':'Mye kan koordineres fra {country}, men fjernbehandling betyr ikke at alle trinn kan utføres uten originaldokument, identitetskontroll eller møte. Dette avklares før du betaler for unødvendige steg.',
'qs':['Kan jeg ordne {t} fra {country} uten å reise til Dubai?','Hva bør jeg kontrollere før jeg notariserer eller legaliserer dokumentet?','Er en skannet PDF nok for denne saken?','Kan mottakeren i EAU kreve en annen ordlyd eller flere fullmakter?','Hva gjør dere hvis dokumentet mitt er utstedt i {country}?'],
'ans':['Ofte kan store deler koordineres på avstand. Vi må likevel kontrollere identitetskrav, dokumenttype og mottaker før vi kan si om hele prosessen kan gjennomføres uten fysisk oppmøte.','Start med mottakeren og formålet. Feil rekkefølge kan føre til at du betaler for en bekreftelse som ikke løser mottakerens krav.','Ikke nødvendigvis. En vanlig skann er ikke det samme som et originaldokument, en bekreftet kopi eller et verifiserbart digitalt originaldokument.','Ja. Et dokument kan være gyldig, men likevel mangle den konkrete fullmakten, formuleringen, oversettelsen eller attesteringen som mottakeren krever.','{local} Vi tilpasser deretter UAE-delen til den faktiske mottakeren.']},
'fi':{
'short':'{t} UAE:ssa käytettävää menettelyä varten; tarkistamme tarkoituksen, vastaanottajan, valtuudet ja asiakirjavaatimukset ennen toimittamista.',
'intro':'{t} on tarkoitettu tilanteisiin, joissa UAE:ssa on hoidettava tietty toimi ja haluat välttää väärän asiakirjamuodon, liian yleiset valtuudet tai puuttuvat vahvistukset. Aloitamme todellisesta käyttötarkoituksesta, vastaanottajasta ja siitä, missä asiakirja annetaan tai allekirjoitetaan.',
'what':'Palvelu koskee nimenomaan kokonaisuutta {t}. Pelkkä asiakirjan otsikko ei ratkaise hyväksyttävyyttä: pankki, DLD, notaari, tuomioistuin, yhtiö tai muu vastaanottaja voi vaatia tiettyä sanamuotoa, henkilötietoja, alkuperäistä asiakirjaa, käännöstä tai vahvistusta.',
'help':'Selvitämme käyttötarkoituksen, vastaanottajan, sijaintimaasi ja jo olemassa olevat asiakirjat. Sen jälkeen koordinoimme oikean järjestyksen laatimiselle, allekirjoittamiselle, notaarivahvistukselle, käännökselle, legalisoinnille tai attestoinnille tarpeen mukaan.',
'before':'Ennen aloittamista tarkistamme nimet ja passitiedot, tarvittavat valtuudet, liitteet, kielen sekä sen, vaatiiko vastaanottaja fyysisen alkuperäisen, oikeaksi todistetun kopion vai varmennettavan digitaalisen alkuperäisen. {local}',
'remote':'Moni vaihe voidaan koordinoida {country}sta, mutta etäpalvelu ei tarkoita, että kaikki vaiheet onnistuvat ilman alkuperäistä asiakirjaa, henkilöllisyyden tarkistusta tai henkilökohtaista käyntiä.',
'qs':['Voinko järjestää palvelun {t} {country}sta matkustamatta Dubaihin?','Mitä pitää tarkistaa ennen notaarivahvistusta tai legalisointia?','Riittääkö skannattu PDF?','Voiko UAE:ssa oleva vastaanottaja vaatia tarkempaa sanamuotoa tai lisävaltuuksia?','Miten {country}ssa annettu asiakirja käsitellään?'],
'ans':['Usein suuri osa prosessista voidaan koordinoida etänä. Ensin on kuitenkin tarkistettava henkilöllisyysmenettely, asiakirjatyyppi ja vastaanottajan vaatimukset.','Aloita käyttötarkoituksesta ja vastaanottajasta. Väärä vahvistusjärjestys voi johtaa tarpeettomiin kustannuksiin tai asiakirjan hylkäämiseen.','Ei aina. Tavallinen skannaus ei automaattisesti vastaa alkuperäistä, oikeaksi todistettua kopiota tai varmennettavaa digitaalista alkuperäistä.','Kyllä. Asiakirja voi olla muodollisesti pätevä mutta silti puutteellinen juuri kyseiseen UAE-menettelyyn.','{local} Tämän jälkeen sovitamme UAE-vaiheet vastaanottavan tahon vaatimuksiin.']},
'es':{
'short':'{t} para una gestión vinculada a EAU, verificando finalidad, destinatario, facultades y requisitos documentales antes de presentar nada.',
'intro':'{t} puede ser necesario cuando debe realizarse una actuación concreta en Emiratos Árabes Unidos y se quiere evitar un documento equivocado, facultades demasiado genéricas o una cadena de legalización incompleta. Empezamos por la operación real, la entidad que recibirá el documento y el país donde se emite o firma.',
'what':'Este servicio se refiere específicamente a {t}. El título del documento no basta: un banco, DLD, notaría, tribunal, empresa u otra entidad receptora puede exigir facultades concretas, determinados datos de identidad, original, traducción o una cadena específica de autenticación.',
'help':'Revisamos el objetivo, el destinatario, dónde se encuentra el cliente y qué documentos ya existen. A partir de ahí coordinamos el orden correcto de redacción, firma, notarización, traducción, legalización o atestación cuando corresponda.',
'before':'Antes de iniciar comprobamos nombres y datos de pasaporte, facultades necesarias, anexos, idioma y si el destinatario exige original físico, copia certificada o un original digital verificable. {local}',
'remote':'Muchas fases pueden coordinarse desde {country}, pero “online” no significa que todos los casos puedan completarse sin original, verificación de identidad o comparecencia. Lo aclaramos antes de iniciar pasos innecesarios.',
'qs':['¿Puedo tramitar {t} desde {country} sin viajar a Dubái?','¿Qué debo comprobar antes de notarizar o legalizar el documento?','¿Es suficiente un PDF escaneado?','¿Puede la entidad de EAU exigir una redacción o facultades diferentes?','¿Qué ocurre si mi documento fue emitido en {country}?'],
'ans':['En muchos casos se puede coordinar gran parte del proceso a distancia, pero primero hay que verificar el método de identificación, el tipo de documento y los requisitos de la entidad receptora.','Hay que empezar por el uso final y el destinatario. Apostilla, legalización y atestación no son trámites intercambiables.','No necesariamente. Un escaneo ordinario no equivale automáticamente a un original, una copia auténtica o un documento digital verificable.','Sí. Un documento puede ser válido y aun así no contener las facultades, el formato, la traducción o las autenticaciones que exige la operación concreta.','{local} Después coordinamos la parte de EAU conforme a la entidad que vaya a aceptar el documento.']},
'it':{
'short':'{t} per una pratica collegata agli EAU, con verifica preventiva di finalità, destinatario, poteri e requisiti documentali.',
'intro':'{t} può essere necessario quando deve essere svolta un’operazione specifica negli Emirati Arabi Uniti e si vogliono evitare un documento sbagliato, poteri troppo generici o una catena di legalizzazione incompleta. Partiamo dall’operazione reale, dall’ente destinatario e dal Paese in cui il documento viene emesso o firmato.',
'what':'Il servizio riguarda specificamente {t}. Il titolo del documento non è sufficiente: banca, DLD, notaio, tribunale, società o altro destinatario possono richiedere poteri precisi, dati identificativi, originale, traduzione o una determinata sequenza di autenticazioni.',
'help':'Verifichiamo finalità, destinatario, Paese in cui si trova il cliente e documenti già disponibili. Coordiniamo poi l’ordine corretto di redazione, firma, autenticazione notarile, traduzione, legalizzazione o attestazione quando necessarie.',
'before':'Prima di iniziare controlliamo nomi e dati del passaporto, poteri necessari, allegati, lingua e se il destinatario richiede originale cartaceo, copia certificata o originale digitale verificabile. {local}',
'remote':'Molte fasi possono essere coordinate da {country}, ma “online” non significa che ogni pratica possa concludersi senza originale, verifica dell’identità o presenza personale. Lo verifichiamo prima di avviare passaggi non necessari.',
'qs':['Posso gestire {t} da {country} senza recarmi a Dubai?','Cosa devo verificare prima della notarizzazione o legalizzazione?','È sufficiente un PDF scansionato?','L’ente negli EAU può richiedere una formulazione o poteri diversi?','Come viene gestito un documento emesso in {country}?'],
'ans':['Spesso gran parte del processo può essere coordinata a distanza, ma vanno prima verificati identificazione, tipo di documento e requisiti del destinatario.','Si parte dall’uso finale e dall’ente che riceverà il documento. Apostille, legalizzazione e attestazione non sono procedure intercambiabili.','Non sempre. Una semplice scansione non equivale automaticamente a un originale, una copia autentica o un originale digitale verificabile.','Sì. Un documento può essere valido ma non contenere i poteri, il formato, la traduzione o le autenticazioni richieste per quella specifica operazione.','{local} Successivamente coordiniamo i passaggi negli EAU in base al destinatario effettivo.']},
'pt':{
'short':'{t} para um procedimento relacionado com os EAU, com verificação prévia da finalidade, destinatário, poderes e requisitos documentais.',
'intro':'{t} pode ser necessário quando existe uma operação concreta a realizar nos Emirados Árabes Unidos e se pretende evitar um documento inadequado, poderes demasiado genéricos ou uma cadeia de legalização incompleta. Começamos pela operação real, pela entidade que receberá o documento e pelo país onde este é emitido ou assinado.',
'what':'Este serviço diz respeito especificamente a {t}. O título do documento, por si só, não garante aceitação: banco, DLD, notário, tribunal, empresa ou outra entidade podem exigir poderes específicos, dados de identificação, original, tradução ou uma sequência própria de autenticações.',
'help':'Analisamos a finalidade, o destinatário, o país onde o cliente se encontra e os documentos já disponíveis. Depois coordenamos a ordem correta de redação, assinatura, reconhecimento notarial, tradução, legalização ou atestação, quando aplicável.',
'before':'Antes de começar verificamos nomes e dados do passaporte, poderes necessários, anexos, idioma e se o destinatário exige original físico, cópia certificada ou original digital verificável. {local}',
'remote':'Muitas etapas podem ser coordenadas a partir de {country}, mas “online” não significa que todos os casos possam ser concluídos sem original, verificação de identidade ou comparência. Confirmamos isso antes de iniciar etapas desnecessárias.',
'qs':['Posso tratar de {t} a partir de {country} sem viajar para o Dubai?','O que devo confirmar antes de reconhecer ou legalizar o documento?','Um PDF digitalizado é suficiente?','A entidade nos EAU pode exigir redação ou poderes diferentes?','Como é tratado um documento emitido em {country}?'],
'ans':['Em muitos casos grande parte do processo pode ser coordenada à distância, mas primeiro é necessário confirmar a identificação, o tipo de documento e as exigências da entidade destinatária.','Deve começar-se pela utilização final e pelo destinatário. Apostila, legalização e atestação não são procedimentos equivalentes.','Nem sempre. Uma digitalização comum não equivale automaticamente a um original, uma cópia certificada ou um original digital verificável.','Sim. Um documento pode ser válido e ainda assim não conter os poderes, formato, tradução ou autenticações exigidos para a operação concreta.','{local} Depois coordenamos a parte dos EAU de acordo com a entidade que efetivamente receberá o documento.']}}
# Complete last 4 records for Batch1 langs by extending their already-reviewed pattern from record 50.
last_titles={
'sv':['Auktoriserad / certifierad översättning','Dokumentkontroll','Dokumenthantering','Internationell dokumentkurir'],
'de':['Beglaubigte / autorisierte Übersetzung','Dokumentenprüfung','Dokumentenbearbeitung','Internationaler Dokumentenkurier'],
'fr':['Traduction certifiée / assermentée','Vérification de documents','Traitement de documents','Courrier international de documents'],
'nl':['Beëdigde / gecertificeerde vertaling','Documentcontrole','Documentverwerking','Internationale documentkoerier'],
'da':['Autoriseret / certificeret oversættelse','Dokumentkontrol','Dokumentbehandling','International dokumentkurér']}
# Copy content structure from previous record but make these four service-specific enough and localized through existing UI language phrases.
last_phr={
'sv':('för gränsöverskridande användning, med kontroll av mottagare och formkrav innan beställning','Vi kontrollerar först var dokumentet ska användas och vilken form mottagaren kräver, så att du inte beställer fel typ av översättning, kontroll eller dokumenthantering.'),
'de':('für die grenzüberschreitende Verwendung, mit Prüfung von Empfänger und Formanforderungen vor der Beauftragung','Wir klären zuerst, wo das Dokument verwendet wird und welche Form der Empfänger verlangt, damit keine ungeeignete Übersetzung, Prüfung oder Bearbeitung beauftragt wird.'),
'fr':('pour une utilisation internationale, avec vérification du destinataire et des exigences de forme avant commande','Nous vérifions d’abord où le document sera utilisé et sous quelle forme il doit être accepté, afin d’éviter une traduction, une vérification ou un traitement inadapté.'),
'nl':('voor grensoverschrijdend gebruik, met controle van ontvanger en vormvereisten vóór de opdracht','We controleren eerst waar het document wordt gebruikt en welke vorm de ontvanger verlangt, zodat geen verkeerde vertaling, controle of verwerking wordt besteld.'),
'da':('til grænseoverskridende brug, med kontrol af modtager og formkrav før bestilling','Vi afklarer først, hvor dokumentet skal bruges, og hvilken form modtageren kræver, så der ikke bestilles en forkert oversættelse, kontrol eller dokumentbehandling.')}
for lang in ['sv','de','fr','nl','da']:
  for j,slug in enumerate(slugs[50:54]):
    base=D[slug][lang]; title=last_titles[lang][j]; suffix,intro=last_phr[lang]
    # retain native existing fields but replace generic description and add explicit title/faq by adapting reviewed prior FAQ style
    base['title']=title; base['shortDescription']=f'{title} {suffix}.'; base['intro']=intro+' '+base.get('intro','')
    # use FAQ from previous service only as linguistic scaffold, replacing service title
    prev=D[slugs[49]][lang]
    faq=[]
    for qa in prev['faq']:
      q=qa['q'].replace(prev['title'],title); a=qa['a']
      faq.append({'q':q,'a':a})
    base['faq']=faq; base['questions']=[x['q'] for x in faq]; base['keywords']=[title,f'{title} Dubai',f'{title} UAE']
# Build 46 pages for each new language.
for lang in ['no','fi','es','it','pt']:
  country,_,_,local=market[lang]; P=phr[lang]
  for i,slug in enumerate(slugs[:46]):
    t=titles[lang][i]; c=D[slug][lang]
    vals={'t':t,'country':country,'local':local}
    c['title']=t
    for key,src in [('shortDescription','short'),('intro','intro'),('what','what'),('howHelp','help'),('beforeYouStart','before'),('remote','remote')]: c[key]=P[src].format(**vals)
    c['faq']=[{'q':q.format(**vals),'a':a.format(**vals)} for q,a in zip(P['qs'],P['ans'])]
    c['questions']=[x['q'] for x in c['faq']]
    c['keywords']=[t,f'{t} Dubai',f'{t} UAE']
    c['market']=country
p.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print('Batch2 records written:',20+5*46)
