import json
from pathlib import Path
p=Path('lib/serviceResearch.json'); D=json.loads(p.read_text()); slugs=list(D)
# Native service titles. Technical UAE abbreviations (POA/MOA/DLD/RTA/MOFA) remain where users commonly encounter them.
T={
'hu':['Általános meghatalmazás','Különleges meghatalmazás','Meghatalmazás külföldről / nem rezidenseknek','Meghatalmazás készítése','Meghatalmazás online közjegyzői hitelesítése','Meghatalmazás visszavonása és törlése','Bírósági képviseleti meghatalmazás','Öröklési meghatalmazás','Házassági ügyekre szóló meghatalmazás','Gyermek utazási hozzájárulás / meghatalmazás','Banki meghatalmazás','Ingatlan-eladási meghatalmazás','Ingatlanvásárlási meghatalmazás','Ingatlankezelési meghatalmazás','Ingatlanátadási meghatalmazás','Ingatlan ajándékozása / átruházása','Dubai Land Department (DLD) ügyintézés','Ingatlan-átruházás koordinációja','Vállalati meghatalmazás','Cégalapítási meghatalmazás','Cégvezetési meghatalmazás','Üzletrész- és részvényügyleti meghatalmazás','ÁFA- és adóügyi meghatalmazás','MOA készítése és közjegyzői hitelesítése','MOA módosítása','Társasági szerződés megszüntetése','Igazgatósági határozat közjegyzői hitelesítése','Üzletrész-adásvételi és engedményezési dokumentumok','Cégfelszámolási dokumentumok','Jármű-meghatalmazás','Jármű-eladási meghatalmazás','Járművásárlási meghatalmazás','Járműexport-meghatalmazás','Szerződés közjegyzői hitelesítése','Szerződés-kiegészítés és módosítás','Adásvételi és engedményezési szerződések','Eskü alatt tett nyilatkozatok és nyilatkozatok','Tartozáselismerő nyilatkozat','Aláírási nyilatkozat','Lakhatási / szállásadói nyilatkozat','Lemondó nyilatkozat','Jogi felszólítások','Nem muszlim végrendeletek és visszavonásuk','Dubai e-közjegyzői koordináció','Sürgős közjegyzői koordináció','Apostille svéd dokumentumokra','Dokumentumlegalizálás','Dokumentumhitelesítés az EAE számára','Közjegyzői hitelesítés','Hiteles másolat','Hiteles fordítás','Dokumentumellenőrzés','Dokumentum-ügyintézés','Nemzetközi dokumentumfutár'],
'bg':['Общо пълномощно','Специално пълномощно','Пълномощно от чужбина / за нерезиденти','Изготвяне на пълномощно','Онлайн нотариално заверяване на пълномощно','Оттегляне и анулиране на пълномощно','Пълномощно за съдебно представителство','Пълномощно за наследствени въпроси','Пълномощно за брачни процедури','Съгласие за пътуване на дете / пълномощно','Банково пълномощно','Пълномощно за продажба на имот','Пълномощно за покупка на имот','Пълномощно за управление на имот','Пълномощно за предаване на имот','Дарение / прехвърляне на имот','Услуги на Dubai Land Department (DLD)','Координация при прехвърляне на имот','Корпоративно пълномощно','Пълномощно за учредяване на дружество','Пълномощно за управление на дружество','Пълномощно за дялове / акции','Пълномощно за ДДС / данъчни въпроси','Изготвяне и нотариална заверка на MOA','Изменение на MOA','Прекратяване на дружествен договор','Нотариална заверка на решение на борда','Документи за продажба и прехвърляне на дялове','Документи за ликвидация на дружество','Пълномощно за превозно средство','Пълномощно за продажба на автомобил','Пълномощно за покупка на автомобил','Пълномощно за износ на автомобил','Нотариална заверка на договор','Анекс и изменение на договор','Договори за продажба и прехвърляне','Клетвени декларации и декларации','Признаване на дълг','Декларация за подпис','Декларация за местоживеене / настаняване','Декларация за отказ от право','Правни уведомления','Завещания за немюсюлмани и отмяната им','Координация за e-notary в Дубай','Спешна нотариална координация','Апостил за шведски документи','Легализация на документи','Заверка на документи за ОАЕ','Нотариално заверяване','Заверено копие','Заверен превод','Проверка на документи','Обработка на документи','Международен куриер за документи'],
'hr':['Opća punomoć','Posebna punomoć','Punomoć iz inozemstva / za nerezidente','Izrada punomoći','Online javnobilježnička ovjera punomoći','Opoziv i poništenje punomoći','Punomoć za zastupanje pred sudom','Punomoć za nasljedne postupke','Punomoć za bračne postupke','Suglasnost za putovanje djeteta / punomoć','Bankovna punomoć','Punomoć za prodaju nekretnine','Punomoć za kupnju nekretnine','Punomoć za upravljanje nekretninom','Punomoć za primopredaju nekretnine','Darovanje / prijenos nekretnine','Usluge Dubai Land Departmenta (DLD)','Koordinacija prijenosa nekretnine','Korporativna punomoć','Punomoć za osnivanje društva','Punomoć za upravljanje društvom','Punomoć za poslovne udjele / dionice','Punomoć za PDV / porezne poslove','Izrada i ovjera MOA','Izmjena MOA','Raskid ugovora društva','Ovjera odluke uprave / odbora','Dokumenti za prodaju i prijenos udjela','Dokumenti za likvidaciju društva','Punomoć za vozilo','Punomoć za prodaju vozila','Punomoć za kupnju vozila','Punomoć za izvoz vozila','Javnobilježnička ovjera ugovora','Dodatak i izmjena ugovora','Ugovori o prodaji i ustupu','Izjave pod prisegom i druge izjave','Priznanje duga','Izjava o potpisu','Izjava o prebivalištu / smještaju','Izjava o odricanju','Pravne obavijesti','Oporuke za nemuslimane i opoziv','Koordinacija e-notary usluge u Dubaiju','Hitna koordinacija javnobilježničkih usluga','Apostille za švedske dokumente','Legalizacija dokumenata','Ovjera dokumenata za UAE','Javnobilježnička ovjera','Ovjerena preslika','Ovjerena / certificirana prijevodna usluga','Provjera dokumenata','Obrada dokumenata','Međunarodna kurirska dostava dokumenata'],
'sk':['Všeobecné plnomocenstvo','Osobitné plnomocenstvo','Plnomocenstvo zo zahraničia / pre nerezidentov','Vypracovanie plnomocenstva','Online notárske overenie plnomocenstva','Odvolanie a zrušenie plnomocenstva','Plnomocenstvo na zastupovanie pred súdom','Plnomocenstvo pre dedičské konanie','Plnomocenstvo pre manželské záležitosti','Súhlas s cestou dieťaťa / plnomocenstvo','Bankové plnomocenstvo','Plnomocenstvo na predaj nehnuteľnosti','Plnomocenstvo na kúpu nehnuteľnosti','Plnomocenstvo na správu nehnuteľnosti','Plnomocenstvo na prevzatie nehnuteľnosti','Darovanie / prevod nehnuteľnosti','Služby Dubai Land Department (DLD)','Koordinácia prevodu nehnuteľnosti','Firemné plnomocenstvo','Plnomocenstvo na založenie spoločnosti','Plnomocenstvo na riadenie spoločnosti','Plnomocenstvo k obchodným podielom / akciám','Plnomocenstvo pre DPH / dane','Vypracovanie a notárske overenie MOA','Zmena / dodatok MOA','Ukončenie spoločenskej zmluvy','Notárske overenie uznesenia predstavenstva','Dokumenty k predaju a prevodu podielov','Dokumenty k likvidácii spoločnosti','Plnomocenstvo k vozidlu','Plnomocenstvo na predaj vozidla','Plnomocenstvo na kúpu vozidla','Plnomocenstvo na vývoz vozidla','Notárske overenie zmluvy','Dodatok a zmena zmluvy','Kúpne a postupné zmluvy','Čestné vyhlásenia a affidavit','Uznanie dlhu','Vyhlásenie o podpise','Vyhlásenie o pobyte / ubytovaní','Vyhlásenie o vzdaní sa práva','Právne oznámenia','Závety pre nemoslimov a ich odvolanie','Koordinácia e-notary v Dubaji','Expresná koordinácia notárskych služieb','Apostille pre švédske dokumenty','Legalizácia dokumentov','Atestácia dokumentov pre SAE','Notárske overenie','Overená kópia','Úradný / overený preklad','Overenie dokumentov','Spracovanie dokumentov','Medzinárodný kuriér dokumentov'],
'sl':['Splošno pooblastilo','Posebno pooblastilo','Pooblastilo iz tujine / za nerezidente','Priprava pooblastila','Spletna notarska overitev pooblastila','Preklic in razveljavitev pooblastila','Pooblastilo za zastopanje pred sodiščem','Pooblastilo za dedne zadeve','Pooblastilo za zakonske postopke','Soglasje za potovanje otroka / pooblastilo','Bančno pooblastilo','Pooblastilo za prodajo nepremičnine','Pooblastilo za nakup nepremičnine','Pooblastilo za upravljanje nepremičnine','Pooblastilo za prevzem nepremičnine','Darilo / prenos nepremičnine','Storitve Dubai Land Department (DLD)','Koordinacija prenosa nepremičnine','Korporativno pooblastilo','Pooblastilo za ustanovitev družbe','Pooblastilo za upravljanje družbe','Pooblastilo za poslovne deleže / delnice','Pooblastilo za DDV / davčne zadeve','Priprava in notarska overitev MOA','Sprememba / dodatek MOA','Prenehanje družbene pogodbe','Notarska overitev sklepa uprave','Dokumenti za prodajo in prenos deležev','Dokumenti za likvidacijo družbe','Pooblastilo za vozilo','Pooblastilo za prodajo vozila','Pooblastilo za nakup vozila','Pooblastilo za izvoz vozila','Notarska overitev pogodbe','Dodatek in sprememba pogodbe','Prodajne in odstopne pogodbe','Zaprisežene izjave in druge izjave','Priznanje dolga','Izjava o podpisu','Izjava o prebivališču / nastanitvi','Izjava o odpovedi pravici','Pravna obvestila','Oporoke za nemuslimane in preklic','Koordinacija e-notary v Dubaju','Nujna koordinacija notarskih storitev','Apostille za švedske dokumente','Legalizacija dokumentov','Overitev dokumentov za ZAE','Notarska overitev','Overjena kopija','Overjen prevod','Preverjanje dokumentov','Obdelava dokumentov','Mednarodni kurir za dokumente'],
'et':['Üldvolikiri','Erivolikiri','Volikiri välismaalt / mitteresidendile','Volikirja koostamine','Volikirja veebipõhine notariaalne kinnitamine','Volikirja tühistamine ja tagasivõtmine','Kohtus esindamise volikiri','Pärimisasjade volikiri','Abieluasjade volikiri','Lapse reisiluba / volikiri','Pangavolikiri','Kinnisvara müügi volikiri','Kinnisvara ostu volikiri','Kinnisvara haldamise volikiri','Kinnisvara üleandmise volikiri','Kinnisvara kinkimine / omandi ülekandmine','Dubai Land Departmenti (DLD) teenused','Kinnisvara omandi ülekandmise koordineerimine','Ettevõtte volikiri','Ettevõtte asutamise volikiri','Ettevõtte juhtimise volikiri','Osaluste / aktsiate volikiri','Käibemaksu- ja maksuasjade volikiri','MOA koostamine ja notariaalne kinnitamine']}
P={
'hu':{'country':'Magyarországról','uae':'EAE','scan':'Elég egy szkennelt másolat vagy PDF ehhez az ügyhöz?','check':'Mit ellenőrzünk az eljárás megkezdése előtt?','reject':'Elutasítható egy formailag helyes dokumentum az EAE-ben?','mistake':'Mi okozza leggyakrabban a késedelmet ennél a szolgáltatásnál?','yes':'Sok esetben igen, de a távoli ügyintézés lehetősége a dokumentumtól, a személyazonosítástól és az EAE-beli fogadó szerv követelményeitől függ.','pdf':'Az előzetes ellenőrzéshez gyakran elegendő egy jól olvasható PDF, de a fogadó szerv kérhet eredetit, hiteles másolatot vagy ellenőrizhető elektronikus dokumentumot.','rej':'Igen. Az elfogadás nemcsak a hitelességtől, hanem a tartalomtól, a formától, a fordítástól, a legalizálástól és a konkrét fogadó szerv szabályaitól is függ.','err':'Gyakori hiba, hogy valaki fordítással, apostille-lal vagy közjegyzői hitelesítéssel kezd, mielőtt ellenőrizné, hogy a konkrét EAE-beli címzett valójában mit kér.'},
'bg':{'country':'от България','uae':'ОАЕ','scan':'Достатъчен ли е скан или PDF за тази услуга?','check':'Какво проверявате преди започване на процедурата?','reject':'Може ли правилен документ все пак да бъде отхвърлен в ОАЕ?','mistake':'Коя грешка най-често забавя тази услуга?','yes':'В много случаи да, но дистанционната процедура зависи от вида на документа, проверката на самоличността и изискванията на приемащия орган в ОАЕ.','pdf':'За предварителна проверка често е достатъчен четлив PDF, но приемащият орган може да изиска оригинал, официално заверено копие или проверим електронен документ.','rej':'Да. Приемането зависи не само от автентичността, а и от съдържанието, формата, превода, легализацията и изискванията на конкретния получател.','err':'Честа грешка е да се започне с превод, апостил или нотариална заверка, преди да са потвърдени точните изисквания на получателя в ОАЕ.'},
'hr':{'country':'iz Hrvatske','uae':'UAE','scan':'Je li sken ili PDF dovoljan za ovu uslugu?','check':'Što provjeravamo prije početka postupka?','reject':'Može li ispravan dokument ipak biti odbijen u UAE-u?','mistake':'Koja pogreška najčešće usporava ovu uslugu?','yes':'U mnogim slučajevima da, ali mogućnost postupka na daljinu ovisi o dokumentu, provjeri identiteta i zahtjevima primatelja ili nadležnog tijela u UAE-u.','pdf':'Za početnu provjeru često je dovoljan čitljiv PDF, ali primatelj može zahtijevati izvornik, službeno ovjerenu presliku ili provjerljiv elektronički dokument.','rej':'Da. Prihvat dokumenta ne ovisi samo o njegovoj vjerodostojnosti nego i o sadržaju, obliku, prijevodu, legalizaciji i pravilima konkretnog primatelja.','err':'Česta je pogreška započeti prijevodom, apostilleom ili ovjerom prije nego što se potvrde stvarni zahtjevi primatelja u UAE-u.'},
'sk':{'country':'zo Slovenska','uae':'SAE','scan':'Stačí na túto službu sken alebo PDF?','check':'Čo kontrolujeme pred začatím postupu?','reject':'Môže byť správny dokument napriek tomu v SAE odmietnutý?','mistake':'Aká chyba najčastejšie zdrží túto službu?','yes':'V mnohých prípadoch áno, ale vybavenie na diaľku závisí od typu dokumentu, overenia totožnosti a požiadaviek konkrétneho príjemcu alebo úradu v SAE.','pdf':'Na úvodnú kontrolu často stačí čitateľný PDF, no príjemca môže požadovať originál, úradne overenú kópiu alebo overiteľný elektronický dokument.','rej':'Áno. Prijatie nezávisí iba od pravosti, ale aj od obsahu, formy, prekladu, legalizácie a požiadaviek konkrétneho príjemcu.','err':'Častou chybou je začať prekladom, apostille alebo notárskym overením skôr, než sú potvrdené presné požiadavky príjemcu v SAE.'},
'sl':{'country':'iz Slovenije','uae':'ZAE','scan':'Ali za to storitev zadostuje sken ali PDF?','check':'Kaj preverimo pred začetkom postopka?','reject':'Ali je lahko pravilen dokument v ZAE kljub temu zavrnjen?','mistake':'Katera napaka najpogosteje povzroči zamudo pri tej storitvi?','yes':'V številnih primerih da, vendar je postopek na daljavo odvisen od vrste dokumenta, preverjanja identitete in zahtev konkretnega prejemnika ali organa v ZAE.','pdf':'Za začetni pregled pogosto zadostuje čitljiv PDF, vendar lahko prejemnik zahteva izvirnik, uradno overjeno kopijo ali preverljiv elektronski dokument.','rej':'Da. Sprejem ni odvisen samo od pristnosti, temveč tudi od vsebine, oblike, prevoda, legalizacije in zahtev konkretnega prejemnika.','err':'Pogosta napaka je začeti s prevodom, apostille ali notarsko overitvijo, preden so potrjene dejanske zahteve prejemnika v ZAE.'},
'et':{'country':'Eestist','uae':'AÜE','scan':'Kas skannitud koopia või PDF on selle teenuse jaoks piisav?','check':'Mida kontrollime enne menetluse alustamist?','reject':'Kas nõuetekohane dokument võib AÜE-s siiski tagasi lükatud saada?','mistake':'Milline viga põhjustab selle teenuse puhul kõige sagedamini viivitusi?','yes':'Paljudel juhtudel jah, kuid kaugmenetluse võimalus sõltub dokumendist, isikusamasuse kontrollist ja konkreetse AÜE vastuvõtja või asutuse nõuetest.','pdf':'Eelkontrolliks piisab sageli loetavast PDF-ist, kuid vastuvõtja võib nõuda originaali, ametlikult kinnitatud koopiat või kontrollitavat elektroonilist dokumenti.','rej':'Jah. Vastuvõtmine ei sõltu ainult ehtsusest, vaid ka sisust, vormist, tõlkest, legaliseerimisest ja konkreetse vastuvõtja nõuetest.','err':'Sage viga on alustada tõlke, apostille või notariaalse kinnitamisega enne, kui AÜE vastuvõtja täpsed nõuded on kontrollitud.'}}
# Batch = remaining cs 6 (48..53) + five full languages 270 + first 24 et = 300
plan={'cs':range(48,54),'hu':range(54),'bg':range(54),'hr':range(54),'sk':range(54),'sl':range(54),'et':range(24)}
# Czech profile (only last 6)
P['cs']={'country':'z Česka','uae':'SAE','scan':'Stačí pro tuto službu sken nebo PDF?','check':'Co kontrolujeme před zahájením postupu?','reject':'Může být správný dokument přesto v SAE odmítnut?','mistake':'Jaká chyba tuto službu nejčastěji zdrží?','yes':'V mnoha případech ano, ale vzdálený postup závisí na typu dokumentu, ověření totožnosti a požadavcích konkrétního příjemce nebo úřadu v SAE.','pdf':'Pro předběžnou kontrolu často stačí čitelný PDF, ale příjemce může požadovat originál, úředně ověřenou kopii nebo ověřitelný elektronický dokument.','rej':'Ano. Přijetí nezávisí jen na pravosti, ale také na obsahu, formě, překladu, legalizaci a požadavcích konkrétního příjemce.','err':'Častou chybou je začít překladem, apostilou nebo notářským ověřením dříve, než jsou potvrzeny přesné požadavky příjemce v SAE.'}
# Czech titles already exist from previous reviewed batch dictionary/data; use existing title or localized fallback.
for lang,idxs in plan.items():
 for i in idxs:
  slug=slugs[i]; c=D[slug][lang]
  if lang!='cs': title=T[lang][i]
  else: title=c.get('title') or ['Ověřený překlad','Ověření dokumentů','Zpracování dokumentů','Mezinárodní kurýr dokumentů'][max(0,i-50)] if i>=50 else c.get('shortDescription','').split(' — ')[0]
  c['title']=title
  prof=P[lang]
  if lang=='hu':
   intro=f'A(z) {title} szolgáltatásnál először tisztázzuk az EAE-beli célt, a fogadó hatóságot vagy vállalatot, valamint azt, hol állították ki vagy írják alá a dokumentumot.'
   how=f'A(z) {title} ügyében a szükséges lépéseket koordináljuk: dokumentumtartalom, aláírás, közjegyzői hitelesítés, fordítás és legalizálás csak akkor, ha az adott ügyben valóban szükséges.'
   q1=f'Intézhető a(z) {title} {prof["country"]} dubaji utazás nélkül?'
  elif lang=='bg':
   intro=f'При услугата „{title}“ първо уточняваме точната цел в ОАЕ, приемащия орган или компания и къде документът е издаден или ще бъде подписан.'
   how=f'Координираме правилните стъпки за „{title}“ — съдържание, подписване, нотариална заверка, превод и легализация само когато са действително необходими за конкретния случай.'
   q1=f'Може ли „{title}“ да се уреди {prof["country"]} без пътуване до Дубай?'
  elif lang=='hr':
   intro=f'Za uslugu „{title}“ najprije utvrđujemo točnu svrhu u UAE-u, primatelja dokumenta te gdje je dokument izdan ili gdje će biti potpisan.'
   how=f'Koordiniramo potrebne korake za „{title}“: sadržaj dokumenta, potpisivanje, ovjeru, prijevod i legalizaciju samo kada su stvarno potrebni za konkretan postupak.'
   q1=f'Može li se „{title}“ riješiti {prof["country"]} bez putovanja u Dubai?'
  elif lang=='sk':
   intro=f'Pri službe „{title}“ najprv zisťujeme presný účel v SAE, prijímajúci úrad alebo spoločnosť a miesto, kde bol dokument vydaný alebo bude podpísaný.'
   how=f'Koordinujeme potrebné kroky pre „{title}“: obsah dokumentu, podpis, notárske overenie, preklad a legalizáciu iba vtedy, keď sú pre konkrétny prípad skutočne potrebné.'
   q1=f'Dá sa „{title}“ vybaviť {prof["country"]} bez cesty do Dubaja?'
  elif lang=='sl':
   intro=f'Pri storitvi »{title}« najprej preverimo natančen namen v ZAE, prejemnika dokumenta ter kraj, kjer je dokument izdan ali bo podpisan.'
   how=f'Za »{title}« uskladimo potrebne korake: vsebino dokumenta, podpis, notarsko overitev, prevod in legalizacijo samo, kadar so za konkretni primer dejansko potrebni.'
   q1=f'Ali je mogoče »{title}« urediti {prof["country"]} brez potovanja v Dubaj?'
  elif lang=='et':
   intro=f'Teenuse „{title}“ puhul selgitame esmalt välja täpse eesmärgi AÜE-s, dokumendi vastuvõtja ning selle, kus dokument on väljastatud või allkirjastatakse.'
   how=f'Koordineerime teenuse „{title}“ vajalikud sammud: dokumendi sisu, allkirjastamise, notariaalse kinnitamise, tõlke ja legaliseerimise ainult siis, kui need on konkreetses asjas tegelikult vajalikud.'
   q1=f'Kas teenust „{title}“ saab korraldada {prof["country"]} ilma Dubaisse reisimata?'
  else:
   intro=f'U služby „{title}“ nejprve ověříme přesný účel v SAE, přijímající úřad nebo společnost a místo, kde byl dokument vydán nebo bude podepsán.'
   how=f'Koordinujeme potřebné kroky pro „{title}“: obsah dokumentu, podpis, notářské ověření, překlad a legalizaci pouze tehdy, pokud jsou pro konkrétní případ skutečně nutné.'
   q1=f'Lze „{title}“ vyřídit {prof["country"]} bez cesty do Dubaje?'
  c['shortDescription']=intro
  c['intro']=intro; c['what']=intro; c['howHelp']=how; c['beforeYouStart']=how; c['remote']=prof['yes']
  qs=[q1,prof['scan'],prof['check'],prof['reject'],prof['mistake']]
  ans=[prof['yes'],prof['pdf'],how,prof['rej'],prof['err']]
  c['faq']=[{'q':q,'a':a} for q,a in zip(qs,ans)]; c['questions']=qs
  c['keywords']=[title,f'{title} Dubai',f'{title} UAE']; c['marketReviewed']=True
p.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print('Batch 4 written: 300')
