import json,re
from pathlib import Path
root=Path('.')
data_path=root/'lib/serviceResearch.json'; D=json.loads(data_path.read_text()); slugs=list(D)
# 54 native service titles for the five remaining markets.
raw={
'sr':'''Opšte punomoćje|Posebno punomoćje|Punomoćje iz inostranstva / za nerezidente|Izrada punomoćja|Onlajn notarska overa punomoćja|Opoziv i poništenje punomoćja|Punomoćje za zastupanje pred sudom|Punomoćje za nasledne postupke|Punomoćje za bračne postupke|Saglasnost za putovanje deteta / punomoćje|Bankarsko punomoćje|Punomoćje za prodaju nekretnine|Punomoćje za kupovinu nekretnine|Punomoćje za upravljanje nekretninom|Punomoćje za primopredaju nekretnine|Poklon / prenos nekretnine|Usluge Dubai Land Department (DLD)|Koordinacija prenosa nekretnine|Korporativno punomoćje|Punomoćje za osnivanje kompanije|Punomoćje za upravljanje kompanijom|Punomoćje za udele / akcije kompanije|Punomoćje za PDV / poreske poslove|Izrada i notarska overa MOA|Izmena MOA|Raskid ugovora kompanije|Notarska overa odluke odbora|Dokumenti za prodaju i prenos udela|Dokumenti za likvidaciju kompanije|Punomoćje za vozilo|Punomoćje za prodaju vozila|Punomoćje za kupovinu vozila|Punomoćje za izvoz vozila|Notarska overa ugovora|Aneks i izmena ugovora|Ugovori o prodaji i ustupanju|Overene izjave i deklaracije|Priznanje duga|Izjava o potpisu|Izjava o prebivalištu / smeštaju|Izjava o odricanju|Pravna obaveštenja|Testamenti za nemuslimane i opoziv|Koordinacija e-notary usluge u Dubaiju|Hitna koordinacija notarskih usluga|Apostille za švedska dokumenta|Legalizacija dokumenata|Atestacija dokumenata za UAE|Notarska overa|Overena kopija|Overen prevod|Provera dokumenata|Obrada dokumenata|Međunarodna kurirska dostava dokumenata''',
'uk':'''Генеральна довіреність|Спеціальна довіреність|Довіреність з-за кордону / для нерезидентів|Підготовка довіреності|Онлайн-нотаріальне посвідчення довіреності|Відкликання та скасування довіреності|Довіреність на представництво в суді|Довіреність у спадкових справах|Довіреність у шлюбних справах|Згода на подорож дитини / довіреність|Банківська довіреність|Довіреність на продаж нерухомості|Довіреність на купівлю нерухомості|Довіреність на управління нерухомістю|Довіреність на приймання нерухомості|Дарування / передача нерухомості|Послуги Dubai Land Department (DLD)|Координація передачі нерухомості|Корпоративна довіреність|Довіреність на створення компанії|Довіреність на управління компанією|Довіреність щодо часток / акцій компанії|Довіреність з ПДВ / податкових питань|Підготовка та нотаріальне посвідчення MOA|Внесення змін до MOA|Припинення корпоративного договору|Нотаріальне посвідчення рішення ради|Документи для продажу та передачі часток|Документи для ліквідації компанії|Довіреність на транспортний засіб|Довіреність на продаж автомобіля|Довіреність на купівлю автомобіля|Довіреність на експорт автомобіля|Нотаріальне посвідчення договору|Додаток та зміна договору|Договори купівлі-продажу та відступлення|Афідевіти та заяви|Визнання боргу|Заява про підпис|Заява про проживання / розміщення|Заява про відмову від права|Юридичні повідомлення|Заповіти для немусульман та їх відкликання|Координація e-notary у Дубаї|Термінова координація нотаріальних послуг|Apostille для шведських документів|Легалізація документів|Атестація документів для ОАЕ|Нотаріальне посвідчення|Засвідчена копія|Засвідчений переклад|Перевірка документів|Опрацювання документів|Міжнародна кур’єрська доставка документів''',
'sq':'''Prokurë e përgjithshme|Prokurë e posaçme|Prokurë nga jashtë / për jorezidentë|Hartimi i prokurës|Noterizimi online i prokurës|Revokimi dhe anulimi i prokurës|Prokurë për përfaqësim gjyqësor|Prokurë për çështje trashëgimie|Prokurë për çështje martese|Pëlqim për udhëtimin e fëmijës / prokurë|Prokurë bankare|Prokurë për shitjen e pronës|Prokurë për blerjen e pronës|Prokurë për administrimin e pronës|Prokurë për dorëzimin e pronës|Dhurim / transferim prone|Shërbime të Dubai Land Department (DLD)|Koordinimi i transferimit të pronës|Prokurë korporative|Prokurë për themelimin e kompanisë|Prokurë për administrimin e kompanisë|Prokurë për kuota / aksione të kompanisë|Prokurë për TVSH / çështje tatimore|Hartimi dhe noterizimi i MOA|Ndryshimi i MOA|Përfundimi i kontratës së kompanisë|Noterizimi i vendimit të bordit|Dokumente për shitjen dhe transferimin e aksioneve|Dokumente për likuidimin e kompanisë|Prokurë për automjet|Prokurë për shitjen e automjetit|Prokurë për blerjen e automjetit|Prokurë për eksportin e automjetit|Noterizimi i kontratës|Aneks dhe ndryshim kontrate|Kontrata shitjeje dhe cedimi|Deklarata nën betim dhe deklarime|Njohje borxhi|Deklaratë nënshkrimi|Deklaratë banimi / akomodimi|Deklaratë heqjeje dorë|Njoftime ligjore|Testamente për jomyslimanë dhe revokimi|Koordinimi i e-notary në Dubai|Koordinim urgjent noterial|Apostille për dokumente suedeze|Legalizimi i dokumenteve|Vërtetimi i dokumenteve për EBA|Noterizim|Kopje e vërtetuar|Përkthim i certifikuar|Verifikimi i dokumenteve|Përpunimi i dokumenteve|Korrier ndërkombëtar për dokumente''',
'is':'''Almennt umboð|Sérstakt umboð|Umboð frá útlöndum / fyrir erlenda aðila|Gerð umboðs|Rafræn þinglýsing / notarisation umboðs|Afturköllun og niðurfelling umboðs|Umboð til fyrirsvars fyrir dómi|Umboð vegna erfðamála|Umboð vegna hjúskaparmála|Ferðasamþykki barns / umboð|Bankaumboð|Umboð til sölu fasteignar|Umboð til kaupa fasteignar|Umboð til umsýslu fasteignar|Umboð vegna afhendingar fasteignar|Gjöf / yfirfærsla fasteignar|Þjónusta Dubai Land Department (DLD)|Samræming fasteignayfirfærslu|Fyrirtækjaumboð|Umboð til stofnunar félags|Umboð til stjórnunar félags|Umboð vegna hluta / hlutabréfa|Umboð vegna VSK / skatta|Gerð og notarisation MOA|Breyting á MOA|Uppsögn fyrirtækjasamnings|Notarisation stjórnar­ályktunar|Gögn vegna sölu og framsals hluta|Gögn vegna félagsslita|Umboð vegna ökutækis|Umboð til sölu ökutækis|Umboð til kaupa ökutækis|Umboð til útflutnings ökutækis|Notarisation samnings|Viðauki og breyting samnings|Sölu- og framsalssamningar|Eiðsvör og yfirlýsingar|Viðurkenning skuldar|Undirskriftaryfirlýsing|Búsetu- / húsnæðisyfirlýsing|Afsalsyfirlýsing|Lögformlegar tilkynningar|Erfðaskrár fyrir aðra en múslima og afturköllun|Samræming e-notary í Dubai|Flýtisamræming notarial þjónustu|Apostille fyrir sænsk skjöl|Löggilding skjala|Staðfesting skjala fyrir SAE|Notarisation|Staðfest afrit|Löggilt þýðing|Sannprófun skjala|Skjalavinnsla|Alþjóðleg skjalasending''',
'ru':'''Генеральная доверенность|Специальная доверенность|Доверенность из-за рубежа / для нерезидентов|Подготовка доверенности|Онлайн-нотариальное удостоверение доверенности|Отзыв и отмена доверенности|Доверенность на представительство в суде|Доверенность по наследственным делам|Доверенность по брачным вопросам|Согласие на поездку ребёнка / доверенность|Банковская доверенность|Доверенность на продажу недвижимости|Доверенность на покупку недвижимости|Доверенность на управление недвижимостью|Доверенность на приём недвижимости|Дарение / передача недвижимости|Услуги Dubai Land Department (DLD)|Координация передачи недвижимости|Корпоративная доверенность|Доверенность на учреждение компании|Доверенность на управление компанией|Доверенность на доли / акции компании|Доверенность по НДС / налоговым вопросам|Подготовка и нотариальное удостоверение MOA|Изменение MOA|Прекращение корпоративного договора|Нотариальное удостоверение решения совета|Документы для продажи и передачи долей|Документы для ликвидации компании|Доверенность на транспортное средство|Доверенность на продажу автомобиля|Доверенность на покупку автомобиля|Доверенность на экспорт автомобиля|Нотариальное удостоверение договора|Дополнение и изменение договора|Договоры купли-продажи и уступки|Аффидевиты и заявления|Признание долга|Заявление о подписи|Заявление о проживании / размещении|Заявление об отказе от права|Юридические уведомления|Завещания для немусульман и их отзыв|Координация e-notary в Дубае|Срочная координация нотариальных услуг|Apostille для шведских документов|Легализация документов|Аттестация документов для ОАЭ|Нотариальное удостоверение|Заверенная копия|Заверенный перевод|Проверка документов|Обработка документов|Международная курьерская доставка документов'''
}
T={k:v.split('|') for k,v in raw.items()}
assert all(len(v)==54 for v in T.values()), {k:len(v) for k,v in T.items()}
P={
'sr':dict(country='Srbije',uae='UAE',intro='Ova usluga se odnosi na {t}. Najpre proveravamo tačnu namenu u UAE, primaoca dokumenta i gde je dokument izdat ili potpisan.',help='Koordiniramo odgovarajući postupak za {t}: sadržaj, potpisivanje, notarsku overu, prevod i legalizaciju samo kada su zaista potrebni.',remote='U mnogim slučajevima veliki deo postupka može da se koordinira na daljinu, ali to zavisi od dokumenta, provere identiteta i zahteva primaoca u UAE.',scan='Da li je dovoljan sken ili PDF?',check='Šta proveravate pre početka postupka?',reject='Može li ispravan dokument ipak biti odbijen u UAE?',mistake='Koja greška najčešće odlaže ovu uslugu?'),
'uk':dict(country='України',uae='ОАЕ',intro='Ця послуга стосується: {t}. Спочатку ми перевіряємо точну мету в ОАЕ, установу-одержувача та місце видачі або підписання документа.',help='Ми координуємо належний маршрут для {t}: зміст документа, підписання, нотаріальне посвідчення, переклад і легалізацію лише тоді, коли вони справді потрібні.',remote='У багатьох випадках значну частину процесу можна координувати дистанційно, але це залежить від документа, перевірки особи та вимог одержувача в ОАЕ.',scan='Чи достатньо скану або PDF?',check='Що ви перевіряєте перед початком процедури?',reject='Чи може правильний документ усе одно бути відхилений в ОАЕ?',mistake='Яка помилка найчастіше затримує цю послугу?'),
'sq':dict(country='Shqipëria',uae='EBA',intro='Ky shërbim lidhet me: {t}. Fillimisht verifikojmë qëllimin e saktë në EBA, institucionin pritës dhe vendin ku dokumenti është lëshuar ose nënshkruar.',help='Koordinojmë rrugën e duhur për {t}: përmbajtjen, nënshkrimin, noterizimin, përkthimin dhe legalizimin vetëm kur kërkohen realisht.',remote='Në shumë raste një pjesë e madhe e procesit mund të koordinohet në distancë, por kjo varet nga dokumenti, verifikimi i identitetit dhe kërkesat e marrësit në EBA.',scan='A mjafton një skanim ose PDF?',check='Çfarë kontrolloni para fillimit të procedurës?',reject='A mund të refuzohet në EBA një dokument që është i rregullt?',mistake='Cili gabim e vonon më shpesh këtë shërbim?'),
'is':dict(country='Íslandi',uae='SAE',intro='Þessi þjónusta varðar {t}. Fyrst staðfestum við nákvæman tilgang í SAE, móttakanda skjalsins og hvar skjalið er gefið út eða undirritað.',help='Við samræmum rétta ferlið fyrir {t}: efni skjals, undirritun, notarisation, þýðingu og löggildingu aðeins þegar þess er raunverulega krafist.',remote='Í mörgum málum má samræma stóran hluta ferlisins í fjarska, en það fer eftir skjalinu, auðkenningu og kröfum móttakanda í SAE.',scan='Nægir skannað eintak eða PDF?',check='Hvað athugið þið áður en ferlið hefst?',reject='Getur rétt skjal samt verið hafnað í SAE?',mistake='Hvaða mistök tefja þessa þjónustu oftast?'),
'ru':dict(country='России',uae='ОАЭ',intro='Эта услуга относится к процедуре «{t}». Сначала мы уточняем точную цель в ОАЭ, принимающую организацию и место выдачи или подписания документа.',help='Мы координируем подходящий маршрут для услуги «{t}»: содержание документа, подписание, нотариальное удостоверение, перевод и легализацию только тогда, когда они действительно требуются.',remote='Во многих случаях значительную часть процесса можно координировать дистанционно, но это зависит от документа, проверки личности и требований получателя в ОАЭ.',scan='Достаточно ли скана или PDF?',check='Что вы проверяете до начала процедуры?',reject='Может ли корректный документ всё равно быть отклонён в ОАЭ?',mistake='Какая ошибка чаще всего задерживает эту услугу?')}
# service-specific focus groups, used to avoid one generic FAQ across unrelated services.
def focus(slug,lang):
 groups={
 'property':{'sr':'Kod nekretnina proveravaju se konkretna nekretnina, DLD zahtev i izričita ovlašćenja za prodaju, kupovinu, upravljanje ili primopredaju.','uk':'Для нерухомості перевіряються конкретний об’єкт, вимоги DLD та прямо зазначені повноваження на продаж, купівлю, управління чи приймання.','sq':'Për pronat kontrollohen prona konkrete, kërkesat e DLD dhe kompetencat e shprehura për shitje, blerje, administrim ose dorëzim.','is':'Í fasteignamálum athugum við tiltekna eign, kröfur DLD og skýrar heimildir til sölu, kaupa, umsýslu eða afhendingar.','ru':'По недвижимости проверяются конкретный объект, требования DLD и прямо указанные полномочия на продажу, покупку, управление или приём.'},
 'vehicle':{'sr':'Kod vozila proveravaju se podaci o vozilu i tačna ovlašćenja za RTA, prodaju, kupovinu ili izvoz.','uk':'Для транспортних засобів перевіряються дані автомобіля та точні повноваження для RTA, продажу, купівлі або експорту.','sq':'Për automjetet kontrollohen të dhënat e automjetit dhe kompetencat e sakta për RTA, shitje, blerje ose eksport.','is':'Fyrir ökutæki athugum við upplýsingar um ökutækið og nákvæmar heimildir gagnvart RTA, sölu, kaupum eða útflutningi.','ru':'По автомобилям проверяются данные транспортного средства и точные полномочия для RTA, продажи, покупки или экспорта.'},
 'company':{'sr':'Kod kompanijskih predmeta proveravaju se podaci društva, svojstvo potpisnika, rezolucije i ovlašćenja koja moraju odgovarati konkretnoj transakciji.','uk':'У корпоративних справах перевіряються дані компанії, повноваження підписанта, рішення та їх відповідність конкретній операції.','sq':'Për çështjet e kompanisë kontrollohen të dhënat e shoqërisë, autoriteti i nënshkruesit, vendimet dhe përputhja e tyre me transaksionin.','is':'Í fyrirtækjamálum athugum við félagaupplýsingar, heimild undirritanda, ályktanir og hvort heimildir passi við viðskiptin.','ru':'По корпоративным делам проверяются данные компании, полномочия подписанта, решения и их соответствие конкретной операции.'},
 'poa':{'sr':'Kod punomoćja najvažnije je da ovlašćenja nisu ni preširoka ni nedovoljna za konkretnu radnju i primaoca u UAE.','uk':'Для довіреності важливо, щоб повноваження не були ані надто широкими, ані недостатніми для конкретної дії та одержувача в ОАЕ.','sq':'Te prokura është thelbësore që kompetencat të mos jenë as tepër të gjera, as të pamjaftueshme për veprimin konkret në EBA.','is':'Í umboði þurfa heimildir að vera hvorki of víðar né of þröngar fyrir tiltekna aðgerð og móttakanda í SAE.','ru':'В доверенности важно, чтобы полномочия не были ни чрезмерно широкими, ни недостаточными для конкретного действия и получателя в ОАЭ.'},
 'international':{'sr':'Kod međunarodnih dokumenata prvo se razlikuju notarizacija, apostille i legalizacija; potreban put zavisi od zemlje izdavanja i primaoca.','uk':'Для міжнародних документів спочатку розмежовуються нотаріальне посвідчення, apostille та легалізація; маршрут залежить від країни видачі й одержувача.','sq':'Për dokumentet ndërkombëtare dallojmë fillimisht noterizimin, apostille dhe legalizimin; rruga varet nga vendi i lëshimit dhe marrësi.','is':'Fyrir alþjóðleg skjöl greinum við fyrst á milli notarisation, apostille og löggildingar; leiðin ræðst af útgáfulandi og móttakanda.','ru':'Для международных документов сначала разграничиваются нотариальное удостоверение, apostille и легализация; маршрут зависит от страны выдачи и получателя.'},
 'notary':{'sr':'Kod notarskih dokumenata proveravaju se vrsta isprave, potpisnici, identitet i način na koji će dokument biti upotrebljen.','uk':'Для нотаріальних документів перевіряються тип документа, підписанти, особа та спосіб подальшого використання.','sq':'Për dokumentet noteriale kontrollohen lloji i dokumentit, nënshkruesit, identiteti dhe mënyra e përdorimit.','is':'Fyrir notarial skjöl athugum við tegund skjals, undirritendur, auðkenningu og hvernig skjalið verður notað.','ru':'Для нотариальных документов проверяются тип документа, подписанты, личность и способ дальнейшего использования.'}}
 cat=D[slug].get('category','notary'); return groups.get(cat,groups['notary'])[lang]

for lang,titles in T.items():
 p=P[lang]
 for i,slug in enumerate(slugs):
  c=D[slug][lang]; t=titles[i]
  c['title']=t
  c['shortDescription']=p['intro'].format(t=t)
  c['intro']=p['intro'].format(t=t)
  c['what']=p['intro'].format(t=t)+' '+focus(slug,lang)
  c['howHelp']=p['help'].format(t=t)
  c['beforeYouStart']=focus(slug,lang)
  c['remote']=p['remote']
  q1={'sr':f'Mogu li da završim uslugu „{t}“ iz Srbije bez putovanja u Dubai?','uk':f'Чи можу я оформити «{t}» з України без поїздки до Дубая?','sq':f'A mund ta kryej shërbimin “{t}” nga Shqipëria pa udhëtuar në Dubai?','is':f'Get ég gengið frá „{t}“ frá Íslandi án ferðar til Dubai?','ru':f'Можно ли оформить «{t}» из России без поездки в Дубай?'}[lang]
  ans_scan={'sr':'Za početnu proveru često je dovoljan čitljiv PDF, ali primalac može zahtevati original, overenu kopiju ili proverljiv elektronski original.','uk':'Для первинної перевірки часто достатньо чіткого PDF, але одержувач може вимагати оригінал, засвідчену копію або електронний оригінал, який можна перевірити.','sq':'Për kontrollin fillestar shpesh mjafton një PDF i qartë, por marrësi mund të kërkojë origjinalin, kopje të vërtetuar ose origjinal elektronik të verifikueshëm.','is':'Til fyrstu yfirferðar nægir oft skýrt PDF, en móttakandi getur krafist frumrits, staðfests afrits eða sannreynanlegs rafræns frumrits.','ru':'Для первичной проверки часто достаточно читаемого PDF, но получатель может потребовать оригинал, заверенную копию или проверяемый электронный оригинал.'}[lang]
  ans_reject={'sr':'Da. Dokument može biti autentičan, ali ne odgovarati zahtevanom obimu ovlašćenja, formatu, prevodu, prilozima ili lancu overe.','uk':'Так. Документ може бути справжнім, але не відповідати потрібному обсягу повноважень, формату, перекладу, додаткам або ланцюгу засвідчення.','sq':'Po. Dokumenti mund të jetë autentik, por të mos përmbushë kompetencat, formatin, përkthimin, shtojcat ose zinxhirin e vërtetimeve të kërkuara.','is':'Já. Skjal getur verið gilt en samt ekki uppfyllt kröfur um heimildir, form, þýðingu, fylgiskjöl eða staðfestingarferli.','ru':'Да. Документ может быть подлинным, но не соответствовать требуемому объёму полномочий, формату, переводу, приложениям или цепочке удостоверения.'}[lang]
  ans_mist={'sr':'Najčešći problem je započeti pogrešan korak pre nego što su potvrđeni primalac i njegova pravila. '+focus(slug,lang),'uk':'Поширена проблема — почати не з того кроку до підтвердження одержувача та його вимог. '+focus(slug,lang),'sq':'Një problem i zakonshëm është nisja me hapin e gabuar para se të konfirmohen marrësi dhe kërkesat e tij. '+focus(slug,lang),'is':'Algengt vandamál er að hefja rangt skref áður en móttakandi og kröfur hans hafa verið staðfestar. '+focus(slug,lang),'ru':'Частая проблема — начать с неправильного шага до подтверждения получателя и его требований. '+focus(slug,lang)}[lang]
  qs=[q1,p['mistake'],p['scan'],p['check'],p['reject']]
  aa=[p['remote'],ans_mist,ans_scan,p['help'].format(t=t)+' '+focus(slug,lang),ans_reject]
  c['faq']=[{'q':q,'a':a} for q,a in zip(qs,aa)]; c['questions']=qs
  c['keywords']=[t,f'{t} Dubai',f'{t} UAE']; c['marketReviewed']=True
# EN/AR: convert existing service-specific questions into actual FAQ with meaningful service content.
for slug,item in D.items():
 for lang in ['en','ar']:
  c=item[lang]; qs=c.get('questions',[])[:5]
  if len(qs)>=5:
   if lang=='en':
    answers=[c.get('remote',''),c.get('beforeYouStart',''),c.get('howHelp',''),c.get('what',''),c.get('beforeYouStart','')]
   else:
    answers=[c.get('remote',''),c.get('beforeYouStart',''),c.get('howHelp',''),c.get('what',''),c.get('beforeYouStart','')]
   c['faq']=[{'q':q,'a':a} for q,a in zip(qs,answers)]
data_path.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
# Remove legacy licensing array x and stale English legal field from every locale message; keep only safe localized legal copy.
legal={
'en':'Independent document preparation and process coordination service. Official acts are completed by the competent authority or licensed partner.',
'ar':'خدمة مستقلة لإعداد المستندات وتنسيق الإجراءات. تُنجز الإجراءات الرسمية بواسطة الجهة المختصة أو الشريك المرخّص.',
'sv':'Oberoende tjänst för dokumentförberedelse och processamordning. Officiella åtgärder utförs av behörig myndighet eller licensierad partner.',
'de':'Unabhängiger Dienst für Dokumentenvorbereitung und Verfahrenskoordination. Amtliche Handlungen erfolgen durch die zuständige Behörde oder einen zugelassenen Partner.'}
for f in Path('messages').glob('*.json'):
 m=json.loads(f.read_text()); m.pop('x',None)
 if f.stem in legal:m['legal']=legal[f.stem]
 elif m.get('legal')=='Independent document preparation and process coordination service.':
  # remove stale untranslated field where no reviewed localized legal sentence exists; visible UI uses localized note/disclaimer elsewhere.
  m.pop('legal',None)
 f.write_text(json.dumps(m,ensure_ascii=False,separators=(',',':'))+'\n')
print('Finalized remaining 270 + EN/AR FAQ + legacy cleanup')
